export const IMAGES = [
  {
    id: 0,
    src: "/image1.jpg",
    title: "Project NEXUS 1",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 1,
    src: "/image1.jpg",
    title: "Project NEXUS 2",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 2,
    src: "/image1.jpg",
    title: "Project NEXUS 3",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 3,
    src: "/image1.jpg",
    title: "Project NEXUS 4",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 4,
    src: "/image1.jpg",
    title: "Project NEXUS 5",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 5,
    src: "/image1.jpg",
    title: "Project NEXUS 6",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 6,
    src: "/image1.jpg",
    title: "Project NEXUS 7",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 7,
    src: "/image1.jpg",
    title: "Project NEXUS 8",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 8,
    src: "/image1.jpg",
    title: "Project NEXUS 9",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 9,
    src: "/image1.jpg",
    title: "Project NEXUS 10",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 10,
    src: "/image1.jpg",
    title: "Project NEXUS 11",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 11,
    src: "/image1.jpg",
    title: "Project NEXUS 12",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 12,
    src: "/image1.jpg",
    title: "Project NEXUS 13",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 13,
    src: "/image1.jpg",
    title: "Project NEXUS 14",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 14,
    src: "/image1.jpg",
    title: "Project NEXUS 15",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 15,
    src: "/image1.jpg",
    title: "Project NEXUS 16",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 16,
    src: "/image1.jpg",
    title: "Project NEXUS 17",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 17,
    src: "/image1.jpg",
    title: "Project NEXUS 18",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 18,
    src: "/image1.jpg",
    title: "Project NEXUS 19",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 19,
    src: "/image1.jpg",
    title: "Project NEXUS 20",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 20,
    src: "/image1.jpg",
    title: "Project NEXUS 21",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 21,
    src: "/image1.jpg",
    title: "Project NEXUS 22",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 22,
    src: "/image1.jpg",
    title: "Project NEXUS 23",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 23,
    src: "/image1.jpg",
    title: "Project NEXUS 24",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 24,
    src: "/image1.jpg",
    title: "Project NEXUS 25",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 25,
    src: "/image1.jpg",
    title: "Project NEXUS 26",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 26,
    src: "/image1.jpg",
    title: "Project NEXUS 27",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 27,
    src: "/image1.jpg",
    title: "Project NEXUS 28",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 28,
    src: "/image1.jpg",
    title: "Project NEXUS 29",
    description: "High-performance rendering with React & Tailwind",
  },
  {
    id: 29,
    src: "/image1.jpg",
    title: "Project NEXUS 30",
    description: "High-performance rendering with React & Tailwind",
  },
] as const;
